sudo: required
dist: trusty

language: node_js

node_js:
  - 5.2

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g firebase-tools
  - npm install

script:
  - npm run build

deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
    tags: true

notifications:
  email:
    on_failure: change
    on_success: change
