export const GET_PRODUCTID_START = 'GET_PRODUCTID_START';
export const GET_PRODUCTID_ERROR = 'GET_PRODUCTID_ERROR';
export const GET_PRODUCTID_SUCCESS = 'GET_PRODUCTID_SUCCESS';

export const GET_PAYMENTID_START = 'GET_PAYMENTID_START';
export const GET_PAYMENTID_ERROR = 'GET_PAYMENTID_ERROR';
export const GET_PAYMENTID_SUCCESS = 'GET_PAYMENTID_SUCCESS';

export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';

export const ADD_STOP_ERROR = 'ADD_STOP_ERROR';
export const ADD_STOP_SUCCESS = 'ADD_STOP_SUCCESS';

export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
