export const GET_PRODUCTID_START = 'GET_PRODUCTID_START';
export const GET_PRODUCTID_ERROR = 'GET_PRODUCTID_ERROR';
export const GET_PRODUCTID_SUCCESS = 'GET_PRODUCTID_SUCCESS';

export const GET_PAYMENTID_START = 'GET_PAYMENTID_START';
export const GET_PAYMENTID_ERROR = 'GET_PAYMENTID_ERROR';
export const GET_PAYMENTID_SUCCESS = 'GET_PAYMENTID_SUCCESS';

export const CREATE_ORDER_START = 'CREATE_ORDER_START';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';

export const ADD_STOP_START = 'ADD_STOP_START';
export const ADD_STOP_ERROR = 'ADD_STOP_ERROR';
export const ADD_STOP_SUCCESS = 'ADD_STOP_SUCCESS';

export const COMPILE_TASK_START = 'COMPILE_TASK_START';
export const COMPILE_TASK_ERROR = 'COMPILE_TASK_ERROR';
export const COMPILE_TASK_SUCCESS = 'COMPILE_TASK_SUCCESS';

export const CALCULATE_TASK_START = 'CALCULATE_TASK_START';
export const CALCULATE_TASK_ERROR = 'CALCULATE_TASK_ERROR';
export const CALCULATE_TASK_SUCCESS = 'CALCULATE_TASK_SUCCESS';

export const UPDATE_STOPINFO_START = 'UPDATE_STOPINFO_START';
export const UPDATE_STOPINFO_ERROR = 'UPDATE_STOPINFO_ERROR';
export const UPDATE_STOPINFO_SUCCESS = 'UPDATE_STOPINFO_SUCCESS';

export const ORDER_TASK_START = 'ORDER_TASK_START';
export const ORDER_TASK_ERROR = 'ORDER_TASK_ERROR';
export const ORDER_TASK_SUCCESS = 'ORDER_TASK_SUCCESS';
