export const GET_PRODUCTID_START = 'GET_PRODUCTID_START';
export const GET_PRODUCTID_ERROR = 'GET_PRODUCTID_ERROR';
export const GET_PRODUCTID_SUCCESS = 'GET_PRODUCTID_SUCCESS';

export const GET_PAYMENTID_START = 'GET_PAYMENTID_START';
export const GET_PAYMENTID_ERROR = 'GET_PAYMENTID_ERROR';
export const GET_PAYMENTID_SUCCESS = 'GET_PAYMENTID_SUCCESS';

export const CREATE_ORDER_START = 'CREATE_ORDER_START';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';

export const ADD_START_START = 'ADD_START_START';
export const ADD_START_STOPADDED = 'ADD_START_STOPADDED';
export const ADD_START_ERROR = 'ADD_START_ERROR';
export const ADD_START_SUCCESS = 'ADD_START_SUCCESS';

export const ADD_END_START = 'ADD_END_START';
export const ADD_END_STOPADDED = 'ADD_END_STOPADDED';
export const ADD_END_ERROR = 'ADD_END_ERROR';
export const ADD_END_SUCCESS = 'ADD_END_SUCCESS';

export const GET_STOPLIST_START = 'GET_STOPLIST_START';
export const GET_STOPLIST_ERROR = 'GET_STOPLIST_ERROR';
export const GET_STOPLIST_SUCCESS = 'GET_STOPLIST_SUCCESS';

export const CALCULATE_TASK_START = 'CALCULATE_TASK_START';
export const CALCULATE_TASK_ERROR = 'CALCULATE_TASK_ERROR';
export const CALCULATE_TASK_SUCCESS = 'CALCULATE_TASK_SUCCESS';

export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
